### PR TITLE
fix: mount misp-guard/mitmproxy ca in misp-core

### LINKED ISSUE #365: MISP-Guard integration leads to TLS handshake errors
Hi, I am currently trying to get misp-docker working with misp-guard.

My workflow was as follows:

1. Ran `git clone https://github.com/MISP/misp-docker`
2. Edited the `.env` file with the minimum required settings:

```
CORE_TAG=v2.5.31
MODULES_TAG=v3.0.5
GUARD_TAG=v1.2
PHP_VER=20240924
PYPI_SETUPTOOLS_VERSION="==80.3.1"
PYPI_SUPERVISOR_VERSION="==4.2.5"

ADMIN_EMAIL=something@example.com
ADMIN_ORG=exampleorg
ADMIN_PASSWORD=password
GPG_PASSPHRASE=randomstring
ENABLE_DB_SETTINGS=false
ENCRYPTION_KEY=randomstring
ENABLE_BACKGROUND_UPDATES=false
MYSQL_HOST=db
MYSQL_USER=mispuser
MYSQL_PASSWORD=securepassword
MYSQL_ROOT_PASSWORD=supersecurepassword
MYSQL_DATABASE=misp
REDIS_HOST=redis
REDIS_PASSWORD=anothersecurepassword

PROXY_ENABLE=true
PROXY_HOST=misp-guard
PROXY_PORT=8888
PROXY_METHOD=MISP-Guard
COMPOSE_PROFILES=misp-guard
GUARD_PORT=8888
GUARD_ARGS=--ssl-insecure -v
```

Logged in at localhost and navigated to **Sync Actions -> Feeds -> Enable Feeds -> Fetch and store all feed data**.
This worked correctly without misp-guard. Afterward, I added the feed URL to `guard/config.json`, which now looks like this:

```json
{
    "allowlist": {
        "urls": ["https://www.circl.lu/doc/misp/feed-osint"],
        "domains": ["www.botvrij.eu"]
    },
    "compartments_rules": {
        "can_reach": {
            "compartment_1": [
                "compartment_1"
            ]
        }
    },
    "instances": {
        "misp_container": {
            "ip": "AUTO_REPLACED_AT_RUNTIME",
            "host": "local-misp",
            "port": 443,
            "compartment_id": "compartment_1",
            "affiliation": "internal",
            "taxonomies_rules": {
                "required_taxonomies": [],
                "allowed_tags": {},
                "blocked_tags": [
                    "tlp:red"
                ]
            },
            "blocked_distribution_levels": [],
            "blocked_sharing_groups_uuids": [],
            "blocked_attribute_types": [],
            "blocked_attribute_categories": [],
            "blocked_object_types": []
        }
}
```

I then repeated the login and feed update steps, but I encountered the following log output:

```
misp-guard-1    | 2026-01-16 14:29:46,669 - mitmproxy.proxy.server - INFO - log:373 - client connect
misp-guard-1    | 2026-01-16 14:29:46,674 - mitmproxy.proxy.server - INFO - log:373 - server connection to www.circl.lu:443 killed before connect: connection not allowed.
misp-guard-1    | 2026-01-16 14:29:46,674 - mitmproxy.proxy.server - INFO - log:373 - client connect
misp-guard-1    | 2026-01-16 14:29:46,684 - mitmproxy.proxy.server - INFO - log:373 - client disconnect
misp-guard-1    | 2026-01-16 14:29:46,842 - mitmproxy.proxy.server - INFO - log:373 - server connect www.botvrij.eu:443 (XX.XX.XX.XX:443)
misp-guard-1    | 2026-01-16 14:29:47,011 - mitmproxy.proxy.server - WARNING - log:373 - Client TLS handshake failed. The client does not trust the proxy's certificate for www.botvrij.eu (tlsv1 alert unknown ca)
misp-guard-1    | 2026-01-16 14:29:47,012 - mitmproxy.proxy.server - INFO - log:373 - client disconnect
misp-guard-1    | 2026-01-16 14:29:47,014 - mitmproxy.proxy.server - INFO - log:373 - server disconnect www.botvrij.eu:443 (XX.XX.XX.XX:443)
```

**Current issues and observations:**

- Connection Denied: Even though I added the exact URL to the allowlist, the log shows: server connection to www.circl.lu:443 killed before connect: connection not allowed.
- TLS Handshake Error: I am also seeing a tlsv1 alert unknown ca error, suggesting the client does not trust the proxy's certificate for www.botvrij.eu.

Based on the documentation, I assumed that entering the exact URL in the allowlist would be sufficient to permit requests. Could you please advise if I am missing a configuration step or if my understanding of the allowlist is incorrect?

### PR DESCRIPTION
**Pull request by righel**
if mitmproxy ca is not configured in `misp-core` proxied requests are dropped by the client.
this PR autoconfigures mitmproxy ca inside `misp-core` at startup

fixes https://github.com/MISP/misp-docker/issues/365

### CODE REVIEW

File: core/files/configure_misp.sh [hunk 1]
```diff
@@ -466,6 +466,15 @@ update_ca_certificates() {
...
 
+configure_misp_guard_ca() {
+    if [[ "$COMPOSE_PROFILES" = "misp-guard" ]]; then
+        echo "... configuring misp-guard CA certificate"
+        chown www-data:www-data /usr/local/share/ca-certificates/misp_guard/mitmproxy-ca.pem
+        sudo -u www-data /var/www/MISP/app/Console/cake Admin setSetting -q "MISP.ca_path" "/usr/local/share/ca-certificates/misp_guard/mitmproxy-ca.pem"
+    fi
+}
+
+
```
Comment (ostefano) [inline core/files/configure_misp.sh]: Nit: only one newline between functions

**Review by ostefano — APPROVED** [review]
LGTM

Will give another look before merging before EOD (or tomorrow at the latest)

**Review by ostefano — APPROVED** [review]
